name: moos-ping
version: '0.1'
summary: MOOS Ping Example
description: |
  The main communication mechanism for all 
  MOOS apps.

confinement: devmode
base: core18

parts:
  moos:
    source: https://github.com/themoos/core-moos/archive/10.0.2.a-release.tar.gz
    build-packages:
      - gcc
      - g++
      - make
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/

apps:
  MOOSDB:
    command: MOOSDB
